// Nationwide PLZ/Ort -> Wohngeld-Mietenstufe lookup, backed by src/content/mietstufen-data.json
// (generated by scripts/generate-mietstufen.mjs from the official WoGV-Anlage + openplzapi.org).
//
// The JSON is dynamically imported so it's code-split into its own chunk and only loaded once a
// user actually reaches the Wohngeld-Rechner's location step, not bundled into the main app.

export type MietstufeRow = [gemeinde: string, kreis: string, land: string, stufe: number, plz: string[]];

export type LocationMatch = {
  /** Short display name, e.g. "München" (honorific suffixes like ", Landeshauptstadt" stripped). */
  name: string;
  kreis: string;
  land: string;
  /** Wohngeld-Mietenstufe, 1 (günstig) – 7 (sehr teuer). */
  stufe: number;
  /** The PLZ that matched the query, or the first known PLZ for a name-based match. */
  plz: string;
};

export type Tier = "guenstig" | "durchschnittlich" | "teuer";

let rowsPromise: Promise<MietstufeRow[]> | null = null;

async function loadRows(): Promise<MietstufeRow[]> {
  rowsPromise ??= import("./mietstufen-data.json").then((mod) => mod.default as unknown as MietstufeRow[]);
  return rowsPromise;
}

function shortName(raw: string): string {
  return raw.split(",")[0].trim();
}

// Loose, diacritic-insensitive fold for user-typed search queries (distinct from the strict
// join-key normalization the generator script uses to match the two source datasets).
function fold(input: string): string {
  return input
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/ß/g, "ss")
    .toLowerCase()
    .trim();
}

const PLZ_QUERY = /^\d{1,5}$/;

export async function searchLocation(query: string, limit = 8): Promise<LocationMatch[]> {
  const q = query.trim();
  if (q.length < 2) return [];

  const rows = await loadRows();
  const isPlzQuery = PLZ_QUERY.test(q);
  const foldedQuery = fold(q);

  type Scored = { row: MietstufeRow; plz: string; rank: number };
  const scored: Scored[] = [];

  for (const row of rows) {
    const [gemeinde, , , , plzList] = row;
    if (isPlzQuery) {
      const matchedPlz = plzList.find((p) => p.startsWith(q));
      if (matchedPlz) scored.push({ row, plz: matchedPlz, rank: 0 });
      continue;
    }
    const foldedName = fold(shortName(gemeinde));
    if (foldedName === foldedQuery) {
      scored.push({ row, plz: plzList[0], rank: 1 });
    } else if (foldedName.startsWith(foldedQuery)) {
      scored.push({ row, plz: plzList[0], rank: 2 });
    } else if (foldedName.includes(foldedQuery)) {
      scored.push({ row, plz: plzList[0], rank: 3 });
    }
  }

  // Within the same match rank, prefer places with more postal codes — a reasonable proxy for
  // population/importance, so e.g. "Hamburg" outranks small same-prefix villages like "Hammah".
  scored.sort(
    (a, b) =>
      a.rank - b.rank ||
      b.row[4].length - a.row[4].length ||
      shortName(a.row[0]).length - shortName(b.row[0]).length,
  );

  return scored.slice(0, limit).map(({ row, plz }) => ({
    name: shortName(row[0]),
    kreis: shortName(row[1]),
    land: row[2],
    stufe: row[3],
    plz,
  }));
}

export function stufeToTier(stufe: number): Tier {
  if (stufe <= 2) return "guenstig";
  if (stufe <= 5) return "durchschnittlich";
  return "teuer";
}
