import type { Locale } from "@/i18n/config";

export type PricingTier = {
  title: string;
  description: string;
  priceLabel: string;
  priceNote?: string;
  features: string[];
  ctaLabel: string;
  ctaHref: string;
  highlight?: boolean;
  badge?: string;
};

// Vier Produkte, jeweils mit Richtpreis (von-bis). Keine "Auf Anfrage"-Karten,
// keine "Coming later"-Karte — siehe Audit-Report §4.2/§4.3.
export const pricingTiers: Record<Locale, PricingTier[]> = {
  de: [
    {
      title: "Brief verstehen",
      description: "Wir erklären dir, was in deinem Behördenbrief steht und was du tun musst.",
      priceLabel: "29–49 €",
      priceNote: "je nach Umfang des Schreibens",
      features: [
        "Verständliche Zusammenfassung deines Briefs",
        "Klarheit über Absender und Anliegen",
        "Fristen, die im Brief stehen",
        "Liste der Unterlagen, die du brauchst",
      ],
      ctaLabel: "Brief hochladen",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Antrag vorbereiten",
      description: "Wir stellen zusammen, was für deinen Antrag fehlt, und bereiten alles vor.",
      priceLabel: "79–149 €",
      priceNote: "je nach Antrag",
      features: [
        "Zusammenstellung aller nötigen Angaben",
        "Abgleich, welche Unterlagen du schon hast",
        "Dein Antrag, vorbereitet zur Einreichung",
        "Ein fester Ansprechpartner für Rückfragen",
      ],
      ctaLabel: "Antrag starten",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Unterlagen-Check",
      description: "Du bekommst eine klare Liste: Was du hast. Was noch fehlt.",
      priceLabel: "39–59 €",
      priceNote: "je nach Anzahl der Dokumente",
      features: [
        "Prüfung deiner vorhandenen Unterlagen",
        "Klare Übersicht: vorhanden / fehlt",
        "Hinweise, wo fehlende Dokumente zu bekommen sind",
        "Ergebnis innerhalb von 48 Stunden",
      ],
      ctaLabel: "Dokumente prüfen lassen",
      ctaHref: "/hilfe-starten?anliegen=unterlagen",
    },
    {
      title: "Papierkram ordnen",
      description: "Wir digitalisieren und sortieren deine Unterlagen — Ordner, Schuhkarton, alles.",
      priceLabel: "149–299 €",
      priceNote: "abhängig vom Umfang, wir nennen dir den Preis nach Sichtung",
      features: [
        "Digitalisierung all deiner Unterlagen",
        "Sortierung nach Kategorien (Wohnen, Familie, Behörden ...)",
        "Ein digitaler Ordner statt Papierstapel",
        "Ansprechpartner für den ganzen Prozess",
      ],
      ctaLabel: "Ordnung schaffen",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
  ],
  en: [
    {
      title: "Understand a letter",
      description: "We explain what's in your official letter and what you need to do.",
      priceLabel: "€29–49",
      priceNote: "depending on the length of the letter",
      features: [
        "Plain-language summary of your letter",
        "Clarity on who sent it and why",
        "Any deadlines stated in the letter",
        "A list of documents you'll need",
      ],
      ctaLabel: "Upload your letter",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Prepare an application",
      description: "We work out what's missing for your application and prepare everything.",
      priceLabel: "€79–149",
      priceNote: "depending on the application",
      features: [
        "Gathering all the information required",
        "Checking which documents you already have",
        "Your application, ready to submit",
        "One fixed contact for follow-up questions",
      ],
      ctaLabel: "Start your application",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Document check",
      description: "You get a clear list: what you have. What's still missing.",
      priceLabel: "€39–59",
      priceNote: "depending on the number of documents",
      features: [
        "Review of the documents you already have",
        "Clear overview: present / missing",
        "Pointers on where to get missing documents",
        "Result within 48 hours",
      ],
      ctaLabel: "Get your documents checked",
      ctaHref: "/hilfe-starten?anliegen=unterlagen",
    },
    {
      title: "Sort out your paperwork",
      description: "We digitize and sort your documents — folders, shoebox, all of it.",
      priceLabel: "€149–299",
      priceNote: "depends on scope, we confirm the price after a first look",
      features: [
        "Digitizing all of your documents",
        "Sorting by category (housing, family, authorities ...)",
        "One digital folder instead of a pile of paper",
        "A single contact for the whole process",
      ],
      ctaLabel: "Get organized",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
  ],
  ar: [
    {
      title: "فهم خطاب",
      description: "نشرح لك ما جاء في خطابك الرسمي وما عليك فعله.",
      priceLabel: "29–49 يورو",
      priceNote: "حسب طول الخطاب",
      features: [
        "ملخص واضح لخطابك",
        "وضوح حول المُرسل والغرض",
        "أي مواعيد نهائية مذكورة في الخطاب",
        "قائمة بالمستندات التي تحتاجها",
      ],
      ctaLabel: "ارفع خطابك",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "تحضير طلب",
      description: "نحدد ما ينقص طلبك ونجهز كل شيء.",
      priceLabel: "79–149 يورو",
      priceNote: "حسب نوع الطلب",
      features: [
        "تجميع كل المعلومات المطلوبة",
        "مراجعة المستندات المتوفرة لديك",
        "طلبك جاهز للتقديم",
        "جهة اتصال ثابتة للاستفسارات",
      ],
      ctaLabel: "ابدأ طلبك",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "فحص المستندات",
      description: "تحصل على قائمة واضحة: ما لديك. وما ينقصك بعد.",
      priceLabel: "39–59 يورو",
      priceNote: "حسب عدد المستندات",
      features: [
        "مراجعة المستندات المتوفرة لديك",
        "نظرة عامة واضحة: موجود / ناقص",
        "إرشادات حول أين تحصل على المستندات الناقصة",
        "النتيجة خلال 48 ساعة",
      ],
      ctaLabel: "افحص مستنداتك",
      ctaHref: "/hilfe-starten?anliegen=unterlagen",
    },
    {
      title: "ترتيب الأوراق",
      description: "نُرقمن ونرتب مستنداتك — ملفات، صندوق أحذية، كل شيء.",
      priceLabel: "149–299 يورو",
      priceNote: "حسب الحجم، نخبرك بالسعر بعد الاطلاع",
      features: [
        "رقمنة جميع مستنداتك",
        "الفرز حسب الفئات (السكن، العائلة، الجهات الرسمية ...)",
        "مجلد رقمي واحد بدلاً من أكوام الأوراق",
        "جهة اتصال واحدة لكل العملية",
      ],
      ctaLabel: "رتّب أوراقك",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
  ],
  tr: [
    {
      title: "Mektubu anla",
      description: "Resmi mektubunda ne yazdığını ve ne yapman gerektiğini açıklıyoruz.",
      priceLabel: "29–49 €",
      priceNote: "mektubun kapsamına göre",
      features: [
        "Mektubunun anlaşılır özeti",
        "Gönderen ve konu hakkında netlik",
        "Mektupta belirtilen süreler",
        "İhtiyacın olan belgelerin listesi",
      ],
      ctaLabel: "Mektubunu yükle",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Başvuru hazırla",
      description: "Başvurun için nelerin eksik olduğunu belirleyip her şeyi hazırlıyoruz.",
      priceLabel: "79–149 €",
      priceNote: "başvuruya göre",
      features: [
        "Gerekli tüm bilgilerin toplanması",
        "Elindeki belgelerin kontrolü",
        "Başvurun, teslime hazır",
        "Sorular için sabit bir iletişim kişisi",
      ],
      ctaLabel: "Başvurunu başlat",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Belge kontrolü",
      description: "Net bir liste alırsın: Elinde ne var. Ne eksik.",
      priceLabel: "39–59 €",
      priceNote: "belge sayısına göre",
      features: [
        "Elindeki belgelerin incelenmesi",
        "Net genel bakış: mevcut / eksik",
        "Eksik belgeleri nereden alacağına dair ipuçları",
        "48 saat içinde sonuç",
      ],
      ctaLabel: "Belgelerini kontrol ettir",
      ctaHref: "/hilfe-starten?anliegen=unterlagen",
    },
    {
      title: "Evrakını düzenle",
      description: "Belgelerini dijitalleştirip düzenliyoruz — klasör, ayakkabı kutusu, hepsi.",
      priceLabel: "149–299 €",
      priceNote: "kapsama göre, önce bakıp fiyatı söylüyoruz",
      features: [
        "Tüm belgelerinin dijitalleştirilmesi",
        "Kategorilere göre sınıflandırma (konut, aile, resmi kurumlar ...)",
        "Kağıt yığını yerine tek bir dijital klasör",
        "Tüm süreç için tek iletişim kişisi",
      ],
      ctaLabel: "Düzeni sağla",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
  ],
  ru: [
    {
      title: "Разобраться в письме",
      description: "Мы объясняем, что написано в вашем официальном письме и что нужно делать.",
      priceLabel: "29–49 €",
      priceNote: "в зависимости от объёма письма",
      features: [
        "Понятное резюме вашего письма",
        "Ясность, кто отправил и зачем",
        "Сроки, указанные в письме",
        "Список нужных документов",
      ],
      ctaLabel: "Загрузить письмо",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Подготовить заявление",
      description: "Мы определяем, чего не хватает для заявления, и готовим всё остальное.",
      priceLabel: "79–149 €",
      priceNote: "в зависимости от заявления",
      features: [
        "Сбор всей необходимой информации",
        "Проверка уже имеющихся документов",
        "Ваше заявление, готовое к подаче",
        "Один постоянный контакт для вопросов",
      ],
      ctaLabel: "Начать заявление",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Проверка документов",
      description: "Вы получаете чёткий список: что есть у вас. Чего ещё не хватает.",
      priceLabel: "39–59 €",
      priceNote: "в зависимости от количества документов",
      features: [
        "Проверка имеющихся у вас документов",
        "Чёткий обзор: есть / отсутствует",
        "Подсказки, где получить недостающие документы",
        "Результат в течение 48 часов",
      ],
      ctaLabel: "Проверить документы",
      ctaHref: "/hilfe-starten?anliegen=unterlagen",
    },
    {
      title: "Разобрать бумаги",
      description: "Мы оцифровываем и сортируем ваши документы — папки, коробки, всё подряд.",
      priceLabel: "149–299 €",
      priceNote: "зависит от объёма, цену назовём после просмотра",
      features: [
        "Оцифровка всех ваших документов",
        "Сортировка по категориям (жильё, семья, ведомства ...)",
        "Одна цифровая папка вместо стопки бумаг",
        "Единый контакт на весь процесс",
      ],
      ctaLabel: "Навести порядок",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
  ],
  uk: [
    {
      title: "Розібратися в листі",
      description: "Ми пояснюємо, що написано у вашому офіційному листі та що потрібно робити.",
      priceLabel: "29–49 €",
      priceNote: "залежно від обсягу листа",
      features: [
        "Зрозуміле резюме вашого листа",
        "Ясність, хто надіслав і навіщо",
        "Строки, вказані в листі",
        "Список потрібних документів",
      ],
      ctaLabel: "Завантажити лист",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Підготувати заяву",
      description: "Ми визначаємо, чого бракує для заяви, і готуємо все інше.",
      priceLabel: "79–149 €",
      priceNote: "залежно від заяви",
      features: [
        "Збір усієї потрібної інформації",
        "Перевірка вже наявних документів",
        "Ваша заява, готова до подання",
        "Один постійний контакт для запитань",
      ],
      ctaLabel: "Почати заяву",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Перевірка документів",
      description: "Ви отримуєте чіткий список: що є у вас. Чого ще бракує.",
      priceLabel: "39–59 €",
      priceNote: "залежно від кількості документів",
      features: [
        "Перевірка наявних у вас документів",
        "Чіткий огляд: є / відсутнє",
        "Підказки, де отримати відсутні документи",
        "Результат протягом 48 годин",
      ],
      ctaLabel: "Перевірити документи",
      ctaHref: "/hilfe-starten?anliegen=unterlagen",
    },
    {
      title: "Розібрати папери",
      description: "Ми оцифровуємо та сортуємо ваші документи — папки, коробки, все підряд.",
      priceLabel: "149–299 €",
      priceNote: "залежить від обсягу, ціну назвемо після перегляду",
      features: [
        "Оцифрування всіх ваших документів",
        "Сортування за категоріями (житло, сім'я, установи ...)",
        "Одна цифрова папка замість стопки паперів",
        "Єдиний контакт на весь процес",
      ],
      ctaLabel: "Навести лад",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
  ],
  pl: [
    {
      title: "Zrozumieć pismo",
      description: "Wyjaśniamy, co jest w twoim urzędowym piśmie i co musisz zrobić.",
      priceLabel: "29–49 €",
      priceNote: "w zależności od zakresu pisma",
      features: [
        "Zrozumiałe podsumowanie twojego pisma",
        "Jasność co do nadawcy i sprawy",
        "Terminy podane w piśmie",
        "Lista potrzebnych dokumentów",
      ],
      ctaLabel: "Prześlij pismo",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Przygotować wniosek",
      description: "Ustalamy, czego brakuje w twoim wniosku, i przygotowujemy resztę.",
      priceLabel: "79–149 €",
      priceNote: "w zależności od wniosku",
      features: [
        "Zebranie wszystkich potrzebnych informacji",
        "Sprawdzenie posiadanych już dokumentów",
        "Twój wniosek gotowy do złożenia",
        "Jeden stały kontakt w razie pytań",
      ],
      ctaLabel: "Rozpocznij wniosek",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Sprawdzenie dokumentów",
      description: "Dostajesz jasną listę: co masz. Czego jeszcze brakuje.",
      priceLabel: "39–59 €",
      priceNote: "w zależności od liczby dokumentów",
      features: [
        "Sprawdzenie posiadanych przez ciebie dokumentów",
        "Jasny przegląd: jest / brakuje",
        "Wskazówki, gdzie zdobyć brakujące dokumenty",
        "Wynik w ciągu 48 godzin",
      ],
      ctaLabel: "Sprawdź dokumenty",
      ctaHref: "/hilfe-starten?anliegen=unterlagen",
    },
    {
      title: "Uporządkować papiery",
      description: "Digitalizujemy i porządkujemy twoje dokumenty — segregatory, pudło, wszystko.",
      priceLabel: "149–299 €",
      priceNote: "zależnie od zakresu, cenę podamy po przejrzeniu",
      features: [
        "Digitalizacja wszystkich twoich dokumentów",
        "Sortowanie według kategorii (mieszkanie, rodzina, urzędy ...)",
        "Jeden cyfrowy folder zamiast stosu papierów",
        "Jeden kontakt na cały proces",
      ],
      ctaLabel: "Zrób porządek",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
  ],
  bg: [
    {
      title: "Разбиране на писмо",
      description: "Обясняваме какво пише в официалното ти писмо и какво трябва да направиш.",
      priceLabel: "29–49 €",
      priceNote: "в зависимост от обема на писмото",
      features: [
        "Разбираемо резюме на писмото ти",
        "Яснота кой го изпраща и защо",
        "Срокове, посочени в писмото",
        "Списък с необходимите документи",
      ],
      ctaLabel: "Качи писмото си",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Подготовка на заявление",
      description: "Установяваме какво липсва за заявлението ти и подготвяме останалото.",
      priceLabel: "79–149 €",
      priceNote: "в зависимост от заявлението",
      features: [
        "Събиране на цялата необходима информация",
        "Проверка на вече наличните документи",
        "Твоето заявление, готово за подаване",
        "Един постоянен контакт за въпроси",
      ],
      ctaLabel: "Започни заявлението",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Проверка на документи",
      description: "Получаваш ясен списък: какво имаш. Какво още липсва.",
      priceLabel: "39–59 €",
      priceNote: "в зависимост от броя документи",
      features: [
        "Проверка на наличните ти документи",
        "Ясен преглед: налично / липсва",
        "Насоки къде да получиш липсващите документи",
        "Резултат до 48 часа",
      ],
      ctaLabel: "Провери документите си",
      ctaHref: "/hilfe-starten?anliegen=unterlagen",
    },
    {
      title: "Подреждане на документи",
      description: "Дигитализираме и подреждаме документите ти — папки, кутия, всичко.",
      priceLabel: "149–299 €",
      priceNote: "според обема, казваме цената след преглед",
      features: [
        "Дигитализиране на всичките ти документи",
        "Сортиране по категории (жилище, семейство, институции ...)",
        "Една цифрова папка вместо купчина хартия",
        "Едно лице за контакт за целия процес",
      ],
      ctaLabel: "Подреди документите",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
  ],
  ro: [
    {
      title: "Înțelege o scrisoare",
      description: "Îți explicăm ce scrie în scrisoarea oficială și ce ai de făcut.",
      priceLabel: "29–49 €",
      priceNote: "în funcție de amploarea scrisorii",
      features: [
        "Rezumat ușor de înțeles al scrisorii tale",
        "Claritate despre expeditor și subiect",
        "Termenele menționate în scrisoare",
        "Lista documentelor de care ai nevoie",
      ],
      ctaLabel: "Încarcă scrisoarea",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Pregătește o cerere",
      description: "Stabilim ce lipsește pentru cererea ta și pregătim restul.",
      priceLabel: "79–149 €",
      priceNote: "în funcție de cerere",
      features: [
        "Strângerea tuturor informațiilor necesare",
        "Verificarea documentelor pe care le ai deja",
        "Cererea ta, gata de trimis",
        "O singură persoană de contact pentru întrebări",
      ],
      ctaLabel: "Începe cererea",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Verificarea actelor",
      description: "Primești o listă clară: ce ai. Ce mai lipsește.",
      priceLabel: "39–59 €",
      priceNote: "în funcție de numărul de documente",
      features: [
        "Verificarea actelor pe care le ai deja",
        "Prezentare clară: prezent / lipsă",
        "Indicații unde poți obține actele lipsă",
        "Rezultat în 48 de ore",
      ],
      ctaLabel: "Verifică-ți actele",
      ctaHref: "/hilfe-starten?anliegen=unterlagen",
    },
    {
      title: "Pune ordine în acte",
      description: "Digitizăm și sortăm actele tale — dosare, cutie de pantofi, tot.",
      priceLabel: "149–299 €",
      priceNote: "în funcție de amploare, spunem prețul după ce le vedem",
      features: [
        "Digitizarea tuturor actelor tale",
        "Sortare pe categorii (locuință, familie, instituții ...)",
        "Un singur dosar digital în loc de teancuri de hârtii",
        "O singură persoană de contact pentru tot procesul",
      ],
      ctaLabel: "Pune ordine",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
  ],
};
