import type { Locale } from "@/i18n/config";

export type PricingTier = {
  title: string;
  description: string;
  priceLabel: string;
  priceNote?: string;
  features: string[];
  ctaLabel: string;
  ctaHref: string;
  highlight?: boolean;
  badge?: string;
};

// Hinweis: Preise sind vorläufige Richtwerte für den Start und noch nicht final
// bepreist. Diese Datei ist zentral verwaltbar und kann angepasst werden,
// sobald die Preisgestaltung final entschieden ist.
export const pricingTiers: Record<Locale, PricingTier[]> = {
  de: [
    {
      title: "Brief-Check",
      description: "Einmalige Unterstützung, um ein einzelnes Behördenschreiben zu verstehen.",
      priceLabel: "Auf Anfrage",
      priceNote: "Richtpreis, abhängig vom Umfang",
      features: [
        "Verständliche Zusammenfassung deines Schreibens",
        "Einordnung von Absender und Anliegen",
        "Hinweis auf erkennbare Fristen",
        "Übersicht benötigter Unterlagen",
      ],
      ctaLabel: "Brief-Check anfragen",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Antragshilfe",
      description: "Unterstützung bei der Vorbereitung eines konkreten Antrags.",
      priceLabel: "Preis abhängig vom Vorgang",
      priceNote: "Wir nennen dir den Preis nach Sichtung deines Anliegens",
      features: [
        "Zusammenstellung benötigter Angaben",
        "Abgleich vorhandener Unterlagen",
        "Strukturierte Vorbereitung deines Antrags",
        "Persönlicher Ansprechpartner bei Rückfragen",
      ],
      ctaLabel: "Antragshilfe anfragen",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Papierkram-Reset",
      description: "Digitalisierung und Organisation größerer Dokumentenmengen.",
      priceLabel: "Individuelles Angebot",
      priceNote: "Abhängig vom Umfang deiner Unterlagen",
      features: [
        "Digitalisierung deiner Unterlagen",
        "Sortierung nach Kategorien",
        "Strukturierte digitale Ablage",
        "Ansprechpartner für den gesamten Prozess",
      ],
      ctaLabel: "Papierkram-Reset anfragen",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
    {
      title: "Antragsbruder Mitgliedschaft",
      description: "Laufende Unterstützung und früher Zugang zu neuen Funktionen.",
      priceLabel: "Coming later",
      priceNote: "Early Access – noch nicht verfügbar",
      features: [
        "Demnächst: laufender digitaler Verwaltungsordner",
        "Demnächst: wiederverwendbare Stammdaten",
        "Demnächst: bevorzugter Zugang zu neuen Funktionen",
      ],
      ctaLabel: "Über Early Access informieren",
      ctaHref: "/kontakt?thema=allgemein",
      badge: "Demnächst",
    },
  ],
  en: [
    {
      title: "Letter check",
      description: "One-off support to understand a single official letter.",
      priceLabel: "On request",
      priceNote: "Indicative price, depending on scope",
      features: [
        "Easy-to-understand summary of your letter",
        "Classification of sender and purpose",
        "Notice of any recognizable deadlines",
        "Overview of required documents",
      ],
      ctaLabel: "Request a letter check",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Application support",
      description: "Support in preparing a specific application.",
      priceLabel: "Price depends on the case",
      priceNote: "We'll tell you the price after reviewing your case",
      features: [
        "Compiling the required information",
        "Checking existing documents",
        "Structured preparation of your application",
        "Personal contact for follow-up questions",
      ],
      ctaLabel: "Request application support",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Paperwork reset",
      description: "Digitizing and organizing larger amounts of documents.",
      priceLabel: "Individual offer",
      priceNote: "Depends on the scope of your documents",
      features: [
        "Digitizing your documents",
        "Sorting by category",
        "Structured digital filing",
        "A single contact for the whole process",
      ],
      ctaLabel: "Request a paperwork reset",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
    {
      title: "Antragsbruder membership",
      description: "Ongoing support and early access to new features.",
      priceLabel: "Coming later",
      priceNote: "Early access – not yet available",
      features: [
        "Coming soon: an ongoing digital administration folder",
        "Coming soon: reusable master data",
        "Coming soon: priority access to new features",
      ],
      ctaLabel: "Get notified about early access",
      ctaHref: "/kontakt?thema=allgemein",
      badge: "Coming soon",
    },
  ],
  ar: [
    {
      title: "فحص الخطاب",
      description: "دعم لمرة واحدة لفهم خطاب رسمي واحد.",
      priceLabel: "عند الطلب",
      priceNote: "سعر إرشادي، يعتمد على النطاق",
      features: [
        "ملخص واضح لخطابك",
        "تحديد المُرسل والغرض",
        "الإشارة إلى أي مواعيد نهائية واضحة",
        "نظرة عامة على المستندات المطلوبة",
      ],
      ctaLabel: "اطلب فحص الخطاب",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "مساعدة في تقديم الطلب",
      description: "دعم في تحضير طلب محدد.",
      priceLabel: "السعر يعتمد على الحالة",
      priceNote: "سنخبرك بالسعر بعد مراجعة حالتك",
      features: [
        "تجميع المعلومات المطلوبة",
        "مراجعة المستندات المتوفرة",
        "تحضير منظم لطلبك",
        "جهة اتصال شخصية للاستفسارات",
      ],
      ctaLabel: "اطلب مساعدة في تقديم الطلب",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "إعادة تنظيم الأوراق",
      description: "رقمنة وتنظيم كميات أكبر من المستندات.",
      priceLabel: "عرض فردي",
      priceNote: "يعتمد على حجم مستنداتك",
      features: [
        "رقمنة مستنداتك",
        "الفرز حسب الفئات",
        "أرشفة رقمية منظمة",
        "جهة اتصال واحدة لكامل العملية",
      ],
      ctaLabel: "اطلب إعادة تنظيم الأوراق",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
    {
      title: "عضوية Antragsbruder",
      description: "دعم مستمر ووصول مبكر إلى الميزات الجديدة.",
      priceLabel: "قريبًا",
      priceNote: "وصول مبكر – غير متاح بعد",
      features: [
        "قريبًا: مجلد إداري رقمي مستمر",
        "قريبًا: بيانات أساسية قابلة لإعادة الاستخدام",
        "قريبًا: وصول مميز إلى الميزات الجديدة",
      ],
      ctaLabel: "اطلع على الوصول المبكر",
      ctaHref: "/kontakt?thema=allgemein",
      badge: "قريبًا",
    },
  ],
  tr: [
    {
      title: "Mektup kontrolü",
      description: "Tek bir resmi mektubu anlamak için tek seferlik destek.",
      priceLabel: "Talep üzerine",
      priceNote: "Kapsama bağlı gösterge fiyat",
      features: [
        "Mektubunun anlaşılır özeti",
        "Gönderenin ve konunun sınıflandırılması",
        "Fark edilen sürelere dair bilgilendirme",
        "Gerekli belgelere genel bakış",
      ],
      ctaLabel: "Mektup kontrolü talep et",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Başvuru desteği",
      description: "Belirli bir başvurunun hazırlanmasında destek.",
      priceLabel: "Fiyat sürece bağlı",
      priceNote: "Durumunu inceledikten sonra sana fiyatı söyleriz",
      features: [
        "Gerekli bilgilerin bir araya getirilmesi",
        "Mevcut belgelerin kontrolü",
        "Başvurunun düzenli şekilde hazırlanması",
        "Sorular için kişisel iletişim kişisi",
      ],
      ctaLabel: "Başvuru desteği talep et",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Evrak sıfırlama",
      description: "Büyük miktarda belgenin dijitalleştirilmesi ve düzenlenmesi.",
      priceLabel: "Bireysel teklif",
      priceNote: "Belgelerinin kapsamına bağlı",
      features: [
        "Belgelerinin dijitalleştirilmesi",
        "Kategorilere göre sınıflandırma",
        "Düzenli dijital arşivleme",
        "Tüm süreç için tek iletişim kişisi",
      ],
      ctaLabel: "Evrak sıfırlama talep et",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
    {
      title: "Antragsbruder üyeliği",
      description: "Sürekli destek ve yeni özelliklere erken erişim.",
      priceLabel: "Yakında",
      priceNote: "Erken erişim – henüz mevcut değil",
      features: [
        "Yakında: sürekli dijital idari klasör",
        "Yakında: yeniden kullanılabilir temel veriler",
        "Yakında: yeni özelliklere öncelikli erişim",
      ],
      ctaLabel: "Erken erişim hakkında bilgi al",
      ctaHref: "/kontakt?thema=allgemein",
      badge: "Yakında",
    },
  ],
  ru: [
    {
      title: "Проверка письма",
      description: "Разовая поддержка, чтобы разобраться в одном официальном письме.",
      priceLabel: "По запросу",
      priceNote: "Ориентировочная цена, зависит от объёма",
      features: [
        "Понятное резюме вашего письма",
        "Определение отправителя и темы",
        "Указание на распознанные сроки",
        "Обзор необходимых документов",
      ],
      ctaLabel: "Запросить проверку письма",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Помощь с заявлением",
      description: "Поддержка в подготовке конкретного заявления.",
      priceLabel: "Цена зависит от случая",
      priceNote: "Мы сообщим цену после рассмотрения вашего вопроса",
      features: [
        "Сбор необходимых данных",
        "Проверка имеющихся документов",
        "Структурированная подготовка заявления",
        "Личный контакт для вопросов",
      ],
      ctaLabel: "Запросить помощь с заявлением",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Разбор документов",
      description: "Оцифровка и организация больших объёмов документов.",
      priceLabel: "Индивидуальное предложение",
      priceNote: "Зависит от объёма ваших документов",
      features: [
        "Оцифровка ваших документов",
        "Сортировка по категориям",
        "Структурированное цифровое хранение",
        "Единый контакт на весь процесс",
      ],
      ctaLabel: "Запросить разбор документов",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
    {
      title: "Членство Antragsbruder",
      description: "Постоянная поддержка и ранний доступ к новым функциям.",
      priceLabel: "Скоро",
      priceNote: "Ранний доступ – пока недоступно",
      features: [
        "Скоро: постоянная цифровая административная папка",
        "Скоро: повторно используемые базовые данные",
        "Скоро: приоритетный доступ к новым функциям",
      ],
      ctaLabel: "Узнать о раннем доступе",
      ctaHref: "/kontakt?thema=allgemein",
      badge: "Скоро",
    },
  ],
  uk: [
    {
      title: "Перевірка листа",
      description: "Одноразова підтримка, щоб розібратися в одному офіційному листі.",
      priceLabel: "За запитом",
      priceNote: "Орієнтовна ціна, залежить від обсягу",
      features: [
        "Зрозуміле резюме вашого листа",
        "Визначення відправника й теми",
        "Позначення розпізнаних строків",
        "Огляд необхідних документів",
      ],
      ctaLabel: "Запросити перевірку листа",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Допомога із заявою",
      description: "Підтримка в підготовці конкретної заяви.",
      priceLabel: "Ціна залежить від випадку",
      priceNote: "Ми повідомимо ціну після розгляду вашого питання",
      features: [
        "Збір необхідних даних",
        "Перевірка наявних документів",
        "Структурована підготовка заяви",
        "Особистий контакт для запитань",
      ],
      ctaLabel: "Запросити допомогу із заявою",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Розбір документів",
      description: "Оцифрування та впорядкування великих обсягів документів.",
      priceLabel: "Індивідуальна пропозиція",
      priceNote: "Залежить від обсягу ваших документів",
      features: [
        "Оцифрування ваших документів",
        "Сортування за категоріями",
        "Структуроване цифрове зберігання",
        "Єдиний контакт на весь процес",
      ],
      ctaLabel: "Запросити розбір документів",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
    {
      title: "Членство Antragsbruder",
      description: "Постійна підтримка та ранній доступ до нових функцій.",
      priceLabel: "Незабаром",
      priceNote: "Ранній доступ – ще не доступно",
      features: [
        "Незабаром: постійна цифрова адміністративна папка",
        "Незабаром: багаторазові базові дані",
        "Незабаром: пріоритетний доступ до нових функцій",
      ],
      ctaLabel: "Дізнатись про ранній доступ",
      ctaHref: "/kontakt?thema=allgemein",
      badge: "Незабаром",
    },
  ],
  pl: [
    {
      title: "Sprawdzenie pisma",
      description: "Jednorazowa pomoc w zrozumieniu jednego pisma urzędowego.",
      priceLabel: "Na zapytanie",
      priceNote: "Cena orientacyjna, w zależności od zakresu",
      features: [
        "Zrozumiałe podsumowanie twojego pisma",
        "Ustalenie nadawcy i sprawy",
        "Wskazanie rozpoznanych terminów",
        "Przegląd wymaganych dokumentów",
      ],
      ctaLabel: "Zapytaj o sprawdzenie pisma",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Pomoc przy wniosku",
      description: "Wsparcie w przygotowaniu konkretnego wniosku.",
      priceLabel: "Cena zależna od sprawy",
      priceNote: "Cenę podamy po zapoznaniu się z twoją sprawą",
      features: [
        "Zebranie potrzebnych informacji",
        "Sprawdzenie posiadanych dokumentów",
        "Uporządkowane przygotowanie wniosku",
        "Osobisty kontakt w razie pytań",
      ],
      ctaLabel: "Zapytaj o pomoc przy wniosku",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Porządkowanie dokumentów",
      description: "Digitalizacja i porządkowanie większych ilości dokumentów.",
      priceLabel: "Oferta indywidualna",
      priceNote: "Zależna od zakresu twoich dokumentów",
      features: [
        "Digitalizacja twoich dokumentów",
        "Sortowanie według kategorii",
        "Uporządkowane cyfrowe archiwum",
        "Jeden kontakt na cały proces",
      ],
      ctaLabel: "Zapytaj o porządkowanie dokumentów",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
    {
      title: "Członkostwo Antragsbruder",
      description: "Stałe wsparcie i wczesny dostęp do nowych funkcji.",
      priceLabel: "Wkrótce",
      priceNote: "Wczesny dostęp – jeszcze niedostępny",
      features: [
        "Wkrótce: stały cyfrowy folder administracyjny",
        "Wkrótce: dane podstawowe wielokrotnego użytku",
        "Wkrótce: priorytetowy dostęp do nowych funkcji",
      ],
      ctaLabel: "Dowiedz się o wczesnym dostępie",
      ctaHref: "/kontakt?thema=allgemein",
      badge: "Wkrótce",
    },
  ],
  bg: [
    {
      title: "Проверка на писмо",
      description: "Еднократна помощ за разбиране на едно официално писмо.",
      priceLabel: "По запитване",
      priceNote: "Ориентировъчна цена, в зависимост от обхвата",
      features: [
        "Разбираемо резюме на писмото ви",
        "Определяне на подателя и темата",
        "Отбелязване на разпознати срокове",
        "Преглед на необходимите документи",
      ],
      ctaLabel: "Заяви проверка на писмо",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Помощ при заявление",
      description: "Подкрепа при подготовката на конкретно заявление.",
      priceLabel: "Цената зависи от случая",
      priceNote: "Ще ви кажем цената след преглед на вашия случай",
      features: [
        "Събиране на необходимите данни",
        "Проверка на наличните документи",
        "Структурирана подготовка на заявлението",
        "Личен контакт при въпроси",
      ],
      ctaLabel: "Заяви помощ при заявление",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Подреждане на документи",
      description: "Дигитализиране и организиране на по-големи количества документи.",
      priceLabel: "Индивидуална оферта",
      priceNote: "В зависимост от обема на вашите документи",
      features: [
        "Дигитализиране на вашите документи",
        "Сортиране по категории",
        "Структурирано цифрово архивиране",
        "Едно лице за контакт за целия процес",
      ],
      ctaLabel: "Заяви подреждане на документи",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
    {
      title: "Членство в Antragsbruder",
      description: "Постоянна подкрепа и ранен достъп до нови функции.",
      priceLabel: "Очаквайте скоро",
      priceNote: "Ранен достъп – все още недостъпен",
      features: [
        "Очаквайте скоро: постоянна цифрова административна папка",
        "Очаквайте скоро: многократно използваеми основни данни",
        "Очаквайте скоро: приоритетен достъп до нови функции",
      ],
      ctaLabel: "Информирайте се за ранния достъп",
      ctaHref: "/kontakt?thema=allgemein",
      badge: "Очаквайте скоро",
    },
  ],
  ro: [
    {
      title: "Verificare scrisoare",
      description: "Sprijin punctual pentru a înțelege o singură scrisoare oficială.",
      priceLabel: "La cerere",
      priceNote: "Preț orientativ, în funcție de amploare",
      features: [
        "Rezumat ușor de înțeles al scrisorii tale",
        "Identificarea expeditorului și a subiectului",
        "Semnalarea termenelor identificate",
        "Prezentare generală a documentelor necesare",
      ],
      ctaLabel: "Solicită verificarea unei scrisori",
      ctaHref: "/hilfe-starten?anliegen=brief",
    },
    {
      title: "Ajutor pentru cerere",
      description: "Sprijin în pregătirea unei cereri concrete.",
      priceLabel: "Prețul depinde de caz",
      priceNote: "Îți spunem prețul după ce analizăm cazul tău",
      features: [
        "Strângerea informațiilor necesare",
        "Verificarea documentelor existente",
        "Pregătirea structurată a cererii tale",
        "Persoană de contact dedicată pentru întrebări",
      ],
      ctaLabel: "Solicită ajutor pentru cerere",
      ctaHref: "/hilfe-starten?anliegen=antrag",
      highlight: true,
    },
    {
      title: "Resetarea actelor",
      description: "Digitizarea și organizarea unor cantități mai mari de documente.",
      priceLabel: "Ofertă individuală",
      priceNote: "În funcție de amploarea actelor tale",
      features: [
        "Digitizarea documentelor tale",
        "Sortare pe categorii",
        "Arhivare digitală structurată",
        "O singură persoană de contact pentru tot procesul",
      ],
      ctaLabel: "Solicită resetarea actelor",
      ctaHref: "/hilfe-starten?anliegen=papierkram",
    },
    {
      title: "Abonament Antragsbruder",
      description: "Sprijin continuu și acces timpuriu la funcții noi.",
      priceLabel: "Disponibil în curând",
      priceNote: "Acces timpuriu – încă indisponibil",
      features: [
        "În curând: un dosar administrativ digital permanent",
        "În curând: date de bază reutilizabile",
        "În curând: acces prioritar la funcții noi",
      ],
      ctaLabel: "Află despre accesul timpuriu",
      ctaHref: "/kontakt?thema=allgemein",
      badge: "În curând",
    },
  ],
};
