import type { Locale } from "@/i18n/config";

export type RoadmapPhase = {
  phase: string;
  title: string;
  status: "jetzt" | "naechste-stufe" | "vision";
  statusLabel: string;
  intro: string;
  points: string[];
  narrativ: string;
};

export const roadmapPhases: Record<Locale, RoadmapPhase[]> = {
  de: [
    {
      phase: "Phase 1",
      title: "Verstehen & Helfen",
      status: "jetzt",
      statusLabel: "Jetzt",
      intro: "Startphase 2026 – Antragsbruder als menschlich unterstützter Verwaltungsservice.",
      points: [
        "Behördenbriefe strukturieren",
        "Antragshilfe",
        "Dokumenten-Check",
        "Papierkram organisieren",
        "Fristen erfassen",
        "Persönliche Unterstützung",
        "Erste digitale Kundenakten",
      ],
      narrativ:
        "Wir lernen anhand realer Verwaltungsfälle, welche Probleme tatsächlich am häufigsten auftreten. Ziel: die ersten hunderten realen Vorgänge verstehen und standardisieren.",
    },
    {
      phase: "Phase 2",
      title: "Digitaler Verwaltungsordner",
      status: "naechste-stufe",
      statusLabel: "Nächste Entwicklungsstufe",
      intro: "Der Kunde soll seine persönlichen Angaben nicht bei jedem Antrag erneut zusammensuchen müssen.",
      points: [
        "Persönlicher Dokumententresor",
        "Intelligente Dokumentensortierung",
        "Strukturierte Kundenprofile",
        "Zentrale Vorgänge",
        "Statusübersichten",
        "Automatisierte Erinnerungen",
        "Bessere Wiederverwendung vorhandener Informationen",
      ],
      narrativ:
        "Der digitale Verwaltungsordner wird zur zentralen Anlaufstelle für alle Unterlagen – geordnet, wiederauffindbar und wiederverwendbar.",
    },
    {
      phase: "Phase 3",
      title: "Automatisierte Standardprozesse",
      status: "vision",
      statusLabel: "Vision",
      intro: "Standardisierte Verwaltungsprozesse werden zunehmend technisch unterstützt – mit Mensch im Kontrollpunkt.",
      points: [
        "Dokument erkannt",
        "Prozess identifiziert",
        "Vorhandene Unterlagen geprüft",
        "Fehlende Unterlagen angefordert",
        "Vorgang vorbereitet",
        "Menschliche bzw. kundenseitige Prüfung",
      ],
      narrativ:
        "Human-in-the-loop bleibt Prinzip: Technologie bereitet vor, Menschen behalten die Kontrolle über jeden wichtigen Schritt.",
    },
    {
      phase: "Phase 4",
      title: "Life Event Administration",
      status: "vision",
      statusLabel: "Langfristige Vision",
      intro: "Nicht mehr „Welches Formular brauche ich?“, sondern „Ich bin umgezogen.“",
      points: [
        "Ich bin umgezogen",
        "Ich habe ein Kind bekommen",
        "Ich habe meinen Job verloren",
        "Ich gehe in Rente",
        "Ein Familienmitglied braucht Pflege",
      ],
      narrativ:
        "Antragsbruder erkennt aus einer Lebenssituation die relevanten administrativen Prozesse – und zeigt, was zu tun ist.",
    },
    {
      phase: "Phase 5",
      title: "Personal Administration OS",
      status: "vision",
      statusLabel: "Langfristiges Ziel",
      intro: "Ein persönliches digitales Verwaltungsbüro für Bürgerinnen und Bürger.",
      points: [
        "Dokumente",
        "Behörden",
        "Fristen",
        "Anträge",
        "Verträge",
        "Familie",
        "Lebensereignisse",
        "Vorgangshistorie",
      ],
      narrativ:
        "Ein Ort für die gesamte private Verwaltung eines Menschen – aufgebaut Schritt für Schritt, nicht als einmaliges Versprechen.",
    },
  ],
  en: [
    {
      phase: "Phase 1",
      title: "Understand & Help",
      status: "jetzt",
      statusLabel: "Now",
      intro: "Launch phase 2026 – Antragsbruder as a human-supported administrative service.",
      points: [
        "Structuring official letters",
        "Application help",
        "Document check",
        "Organizing paperwork",
        "Tracking deadlines",
        "Personal support",
        "First digital customer files",
      ],
      narrativ:
        "We're learning from real administrative cases which problems actually come up most often. Goal: understand and standardize the first few hundred real cases.",
    },
    {
      phase: "Phase 2",
      title: "Digital Administration Folder",
      status: "naechste-stufe",
      statusLabel: "Next development stage",
      intro: "You shouldn't have to gather your personal details from scratch for every single application.",
      points: [
        "Personal document vault",
        "Smart document sorting",
        "Structured customer profiles",
        "Central case overview",
        "Status overviews",
        "Automated reminders",
        "Better reuse of existing information",
      ],
      narrativ:
        "The digital administration folder becomes the central place for all your documents – organized, easy to find, and reusable.",
    },
    {
      phase: "Phase 3",
      title: "Automated standard processes",
      status: "vision",
      statusLabel: "Vision",
      intro: "Standardized administrative processes are increasingly supported by technology – with a human at the control point.",
      points: [
        "Document recognized",
        "Process identified",
        "Existing documents checked",
        "Missing documents requested",
        "Case prepared",
        "Human / customer review",
      ],
      narrativ:
        "Human-in-the-loop remains the principle: technology prepares, people keep control over every important step.",
    },
    {
      phase: "Phase 4",
      title: "Life Event Administration",
      status: "vision",
      statusLabel: "Long-term vision",
      intro: "No longer \"Which form do I need?\", but \"I just moved.\"",
      points: [
        "I moved",
        "I had a child",
        "I lost my job",
        "I'm retiring",
        "A family member needs care",
      ],
      narrativ:
        "Antragsbruder recognizes the relevant administrative processes from a life situation – and shows you what to do.",
    },
    {
      phase: "Phase 5",
      title: "Personal Administration OS",
      status: "vision",
      statusLabel: "Long-term goal",
      intro: "A personal digital administration office for every citizen.",
      points: [
        "Documents",
        "Authorities",
        "Deadlines",
        "Applications",
        "Contracts",
        "Family",
        "Life events",
        "Case history",
      ],
      narrativ:
        "One place for a person's entire private administration – built step by step, not promised all at once.",
    },
  ],
  ar: [
    {
      phase: "Phase 1",
      title: "الفهم والمساعدة",
      status: "jetzt",
      statusLabel: "الآن",
      intro: "مرحلة الانطلاق 2026 – Antragsbruder كخدمة إدارية بدعم بشري.",
      points: [
        "تنظيم الرسائل الرسمية",
        "المساعدة في تقديم الطلبات",
        "فحص المستندات",
        "تنظيم الأوراق",
        "تسجيل المواعيد النهائية",
        "دعم شخصي",
        "أولى الملفات الرقمية للعملاء",
      ],
      narrativ:
        "نتعلم من حالات إدارية حقيقية ما هي المشكلات الأكثر شيوعًا فعليًا. الهدف: فهم وتوحيد أول بضع مئات من الحالات الحقيقية.",
    },
    {
      phase: "Phase 2",
      title: "المجلد الإداري الرقمي",
      status: "naechste-stufe",
      statusLabel: "المرحلة التطويرية التالية",
      intro: "لا ينبغي أن تضطر إلى جمع بياناتك الشخصية من جديد مع كل طلب.",
      points: [
        "خزانة مستندات شخصية",
        "فرز ذكي للمستندات",
        "ملفات عملاء منظمة",
        "نظرة مركزية على جميع الإجراءات",
        "نظرة عامة على الحالة",
        "تذكيرات تلقائية",
        "إعادة استخدام أفضل للمعلومات الموجودة",
      ],
      narrativ:
        "يصبح المجلد الإداري الرقمي نقطة الاتصال المركزية لجميع المستندات – منظمة، قابلة للاسترجاع وقابلة لإعادة الاستخدام.",
    },
    {
      phase: "Phase 3",
      title: "عمليات قياسية مؤتمتة",
      status: "vision",
      statusLabel: "رؤية",
      intro: "العمليات الإدارية المعيارية تحظى بدعم تقني متزايد – مع بقاء الإنسان نقطة التحكم.",
      points: [
        "تم التعرف على المستند",
        "تم تحديد العملية",
        "تم فحص المستندات الموجودة",
        "تم طلب المستندات الناقصة",
        "تم تجهيز الإجراء",
        "مراجعة بشرية / من قبل العميل",
      ],
      narrativ:
        "يبقى مبدأ الإنسان في الحلقة قائمًا: التقنية تُجهّز، والأشخاص يحتفظون بالسيطرة على كل خطوة مهمة.",
    },
    {
      phase: "Phase 4",
      title: "إدارة أحداث الحياة",
      status: "vision",
      statusLabel: "رؤية طويلة المدى",
      intro: "لم يعد السؤال «أي استمارة أحتاجها؟»، بل «لقد انتقلت للتو».",
      points: [
        "لقد انتقلت للتو",
        "رُزقت بطفل",
        "فقدت وظيفتي",
        "أنا على وشك التقاعد",
        "أحد أفراد عائلتي بحاجة إلى رعاية",
      ],
      narrativ:
        "يتعرف Antragsbruder على العمليات الإدارية ذات الصلة انطلاقًا من موقف حياتي – ويوضح لك ما ينبغي فعله.",
    },
    {
      phase: "Phase 5",
      title: "نظام إدارة شخصي شامل",
      status: "vision",
      statusLabel: "هدف طويل المدى",
      intro: "مكتب إداري رقمي شخصي لكل مواطن.",
      points: [
        "المستندات",
        "الجهات الرسمية",
        "المواعيد النهائية",
        "الطلبات",
        "العقود",
        "العائلة",
        "أحداث الحياة",
        "سجل الإجراءات",
      ],
      narrativ:
        "مكان واحد لكل الشؤون الإدارية الخاصة بالشخص – يُبنى خطوة بخطوة، لا كوعد يتحقق دفعة واحدة.",
    },
  ],
  tr: [
    {
      phase: "Phase 1",
      title: "Anlamak & Yardım Etmek",
      status: "jetzt",
      statusLabel: "Şimdi",
      intro: "2026 başlangıç aşaması – Antragsbruder, insan destekli bir idari hizmet olarak.",
      points: [
        "Resmi yazıları düzenleme",
        "Başvuru yardımı",
        "Belge kontrolü",
        "Evrak işlerini düzenleme",
        "Süreleri takip etme",
        "Kişisel destek",
        "İlk dijital müşteri dosyaları",
      ],
      narrativ:
        "Gerçek idari vakalardan hangi sorunların en sık ortaya çıktığını öğreniyoruz. Hedefimiz: ilk birkaç yüz gerçek vakayı anlamak ve standartlaştırmak.",
    },
    {
      phase: "Phase 2",
      title: "Dijital İdari Klasör",
      status: "naechste-stufe",
      statusLabel: "Sonraki gelişim aşaması",
      intro: "Her başvuruda kişisel bilgilerini yeniden bir araya getirmek zorunda kalmamalısın.",
      points: [
        "Kişisel belge kasası",
        "Akıllı belge sıralama",
        "Yapılandırılmış müşteri profilleri",
        "Merkezi süreç görünümü",
        "Durum genel bakışı",
        "Otomatik hatırlatmalar",
        "Mevcut bilgilerin daha iyi kullanılması",
      ],
      narrativ:
        "Dijital idari klasör, tüm belgelerin merkezi buluşma noktası olur – düzenli, kolayca bulunabilir ve yeniden kullanılabilir.",
    },
    {
      phase: "Phase 3",
      title: "Otomatikleştirilmiş standart süreçler",
      status: "vision",
      statusLabel: "Vizyon",
      intro: "Standart idari süreçler giderek daha fazla teknik destek alıyor – kontrol noktasında insan kalmaya devam ediyor.",
      points: [
        "Belge tanındı",
        "Süreç belirlendi",
        "Mevcut belgeler kontrol edildi",
        "Eksik belgeler talep edildi",
        "Süreç hazırlandı",
        "İnsan / müşteri tarafından kontrol",
      ],
      narrativ:
        "İnsan kontrolü ilkesi geçerliliğini koruyor: teknoloji hazırlar, önemli her adımın kontrolü insanlarda kalır.",
    },
    {
      phase: "Phase 4",
      title: "Yaşam Olayı Yönetimi",
      status: "vision",
      statusLabel: "Uzun vadeli vizyon",
      intro: "Artık \"Hangi formu doldurmalıyım?\" değil, \"Taşındım.\"",
      points: [
        "Taşındım",
        "Bir çocuğum oldu",
        "İşimi kaybettim",
        "Emekli oluyorum",
        "Bir aile üyemin bakıma ihtiyacı var",
      ],
      narrativ:
        "Antragsbruder, bir yaşam durumundan ilgili idari süreçleri tanır – ve ne yapman gerektiğini gösterir.",
    },
    {
      phase: "Phase 5",
      title: "Kişisel İdari İşletim Sistemi",
      status: "vision",
      statusLabel: "Uzun vadeli hedef",
      intro: "Her vatandaş için kişisel dijital bir idari ofis.",
      points: [
        "Belgeler",
        "Kurumlar",
        "Süreler",
        "Başvurular",
        "Sözleşmeler",
        "Aile",
        "Yaşam olayları",
        "Süreç geçmişi",
      ],
      narrativ:
        "Bir kişinin tüm özel idari işleri için tek bir yer – tek seferde vaat edilen değil, adım adım inşa edilen.",
    },
  ],
  ru: [
    {
      phase: "Phase 1",
      title: "Понимать и помогать",
      status: "jetzt",
      statusLabel: "Сейчас",
      intro: "Стартовая фаза 2026 года – Antragsbruder как административный сервис с человеческой поддержкой.",
      points: [
        "Структурирование писем от ведомств",
        "Помощь с заявлениями",
        "Проверка документов",
        "Организация бумажной волокиты",
        "Отслеживание сроков",
        "Личная поддержка",
        "Первые цифровые дела клиентов",
      ],
      narrativ:
        "Мы учимся на реальных административных случаях, какие проблемы возникают чаще всего. Цель: понять и стандартизировать первые несколько сотен реальных обращений.",
    },
    {
      phase: "Phase 2",
      title: "Цифровая административная папка",
      status: "naechste-stufe",
      statusLabel: "Следующий этап развития",
      intro: "Клиенту не должно приходиться заново собирать личные данные для каждого заявления.",
      points: [
        "Личное хранилище документов",
        "Умная сортировка документов",
        "Структурированные профили клиентов",
        "Централизованный обзор дел",
        "Обзор статусов",
        "Автоматические напоминания",
        "Более эффективное повторное использование имеющихся данных",
      ],
      narrativ:
        "Цифровая административная папка становится центральным местом хранения всех документов – упорядоченным, легко находимым и пригодным для повторного использования.",
    },
    {
      phase: "Phase 3",
      title: "Автоматизированные стандартные процессы",
      status: "vision",
      statusLabel: "Видение",
      intro: "Стандартизированные административные процессы всё больше поддерживаются технологиями – при этом человек остаётся точкой контроля.",
      points: [
        "Документ распознан",
        "Процесс определён",
        "Имеющиеся документы проверены",
        "Запрошены недостающие документы",
        "Дело подготовлено",
        "Проверка человеком / клиентом",
      ],
      narrativ:
        "Принцип «человек в контуре» остаётся неизменным: технологии готовят, люди сохраняют контроль над каждым важным шагом.",
    },
    {
      phase: "Phase 4",
      title: "Управление жизненными событиями",
      status: "vision",
      statusLabel: "Долгосрочное видение",
      intro: "Больше не «Какая форма мне нужна?», а «Я переехал».",
      points: [
        "Я переехал",
        "У меня родился ребёнок",
        "Я потерял работу",
        "Я выхожу на пенсию",
        "Члену семьи нужен уход",
      ],
      narrativ:
        "Antragsbruder распознаёт по жизненной ситуации нужные административные процессы – и показывает, что нужно сделать.",
    },
    {
      phase: "Phase 5",
      title: "Personal Administration OS",
      status: "vision",
      statusLabel: "Долгосрочная цель",
      intro: "Персональный цифровой административный офис для каждого гражданина.",
      points: [
        "Документы",
        "Ведомства",
        "Сроки",
        "Заявления",
        "Договоры",
        "Семья",
        "Жизненные события",
        "История обращений",
      ],
      narrativ:
        "Единое место для всех личных административных дел человека – выстраиваемое шаг за шагом, а не обещанное разом.",
    },
  ],
  uk: [
    {
      phase: "Phase 1",
      title: "Розуміти та допомагати",
      status: "jetzt",
      statusLabel: "Зараз",
      intro: "Стартова фаза 2026 року – Antragsbruder як адміністративний сервіс із людською підтримкою.",
      points: [
        "Структурування листів від установ",
        "Допомога із заявами",
        "Перевірка документів",
        "Впорядкування паперів",
        "Відстеження термінів",
        "Особиста підтримка",
        "Перші цифрові справи клієнтів",
      ],
      narrativ:
        "Ми вчимося на реальних адміністративних випадках, які проблеми виникають найчастіше. Мета: зрозуміти й стандартизувати перші кілька сотень реальних справ.",
    },
    {
      phase: "Phase 2",
      title: "Цифрова адміністративна папка",
      status: "naechste-stufe",
      statusLabel: "Наступний етап розвитку",
      intro: "Клієнту не повинно доводитись щоразу заново збирати особисті дані для кожної заяви.",
      points: [
        "Особисте сховище документів",
        "Розумне сортування документів",
        "Структуровані профілі клієнтів",
        "Централізований огляд справ",
        "Огляд статусів",
        "Автоматичні нагадування",
        "Краще повторне використання наявної інформації",
      ],
      narrativ:
        "Цифрова адміністративна папка стає центральним місцем для всіх документів – упорядкованим, легко доступним і придатним для повторного використання.",
    },
    {
      phase: "Phase 3",
      title: "Автоматизовані стандартні процеси",
      status: "vision",
      statusLabel: "Візія",
      intro: "Стандартизовані адміністративні процеси дедалі більше підтримуються технологіями – людина залишається точкою контролю.",
      points: [
        "Документ розпізнано",
        "Процес визначено",
        "Наявні документи перевірено",
        "Запитано відсутні документи",
        "Справу підготовлено",
        "Перевірка людиною / клієнтом",
      ],
      narrativ:
        "Принцип «людина в циклі» залишається незмінним: технологія готує, люди зберігають контроль над кожним важливим кроком.",
    },
    {
      phase: "Phase 4",
      title: "Управління життєвими подіями",
      status: "vision",
      statusLabel: "Довгострокова візія",
      intro: "Більше не «Яка форма мені потрібна?», а «Я переїхав».",
      points: [
        "Я переїхав",
        "У мене народилася дитина",
        "Я втратив роботу",
        "Я виходжу на пенсію",
        "Члену родини потрібен догляд",
      ],
      narrativ:
        "Antragsbruder розпізнає за життєвою ситуацією потрібні адміністративні процеси – і показує, що робити далі.",
    },
    {
      phase: "Phase 5",
      title: "Personal Administration OS",
      status: "vision",
      statusLabel: "Довгострокова мета",
      intro: "Особистий цифровий адміністративний офіс для кожного громадянина.",
      points: [
        "Документи",
        "Установи",
        "Терміни",
        "Заяви",
        "Договори",
        "Родина",
        "Життєві події",
        "Історія справ",
      ],
      narrativ:
        "Одне місце для всієї приватної адміністративної діяльності людини – яке будується крок за кроком, а не обіцяється одразу.",
    },
  ],
  pl: [
    {
      phase: "Phase 1",
      title: "Rozumieć i pomagać",
      status: "jetzt",
      statusLabel: "Teraz",
      intro: "Faza startowa 2026 – Antragsbruder jako usługa administracyjna wspierana przez ludzi.",
      points: [
        "Porządkowanie pism urzędowych",
        "Pomoc we wnioskach",
        "Sprawdzanie dokumentów",
        "Porządkowanie papierów",
        "Śledzenie terminów",
        "Osobiste wsparcie",
        "Pierwsze cyfrowe akta klientów",
      ],
      narrativ:
        "Uczymy się na podstawie prawdziwych spraw administracyjnych, jakie problemy pojawiają się najczęściej. Cel: zrozumieć i ustandaryzować pierwsze kilkaset rzeczywistych spraw.",
    },
    {
      phase: "Phase 2",
      title: "Cyfrowy folder administracyjny",
      status: "naechste-stufe",
      statusLabel: "Kolejny etap rozwoju",
      intro: "Klient nie powinien musieć za każdym razem od nowa zbierać swoich danych osobowych przy każdym wniosku.",
      points: [
        "Osobisty sejf na dokumenty",
        "Inteligentne sortowanie dokumentów",
        "Uporządkowane profile klientów",
        "Centralny przegląd spraw",
        "Przegląd statusów",
        "Automatyczne przypomnienia",
        "Lepsze wykorzystanie istniejących informacji",
      ],
      narrativ:
        "Cyfrowy folder administracyjny staje się centralnym miejscem dla wszystkich dokumentów – uporządkowanym, łatwym do odnalezienia i wielokrotnego użytku.",
    },
    {
      phase: "Phase 3",
      title: "Zautomatyzowane standardowe procesy",
      status: "vision",
      statusLabel: "Wizja",
      intro: "Standardowe procesy administracyjne są coraz bardziej wspierane technologicznie – z człowiekiem jako punktem kontroli.",
      points: [
        "Dokument rozpoznany",
        "Proces zidentyfikowany",
        "Sprawdzono istniejące dokumenty",
        "Poproszono o brakujące dokumenty",
        "Sprawa przygotowana",
        "Weryfikacja przez człowieka / klienta",
      ],
      narrativ:
        "Zasada „człowiek w pętli” pozostaje niezmienna: technologia przygotowuje, ludzie zachowują kontrolę nad każdym ważnym krokiem.",
    },
    {
      phase: "Phase 4",
      title: "Zarządzanie wydarzeniami życiowymi",
      status: "vision",
      statusLabel: "Długoterminowa wizja",
      intro: "Już nie „Jaki formularz jest mi potrzebny?”, lecz „Przeprowadziłem się”.",
      points: [
        "Przeprowadziłem się",
        "Urodziło mi się dziecko",
        "Straciłem pracę",
        "Przechodzę na emeryturę",
        "Członek rodziny potrzebuje opieki",
      ],
      narrativ:
        "Antragsbruder rozpoznaje na podstawie sytuacji życiowej odpowiednie procesy administracyjne – i pokazuje, co należy zrobić.",
    },
    {
      phase: "Phase 5",
      title: "Personal Administration OS",
      status: "vision",
      statusLabel: "Cel długoterminowy",
      intro: "Osobiste cyfrowe biuro administracyjne dla każdego obywatela.",
      points: [
        "Dokumenty",
        "Urzędy",
        "Terminy",
        "Wnioski",
        "Umowy",
        "Rodzina",
        "Wydarzenia życiowe",
        "Historia spraw",
      ],
      narrativ:
        "Jedno miejsce na całą prywatną administrację danej osoby – budowane krok po kroku, a nie obiecane od razu.",
    },
  ],
  bg: [
    {
      phase: "Phase 1",
      title: "Разбиране и помощ",
      status: "jetzt",
      statusLabel: "Сега",
      intro: "Стартова фаза 2026 г. – Antragsbruder като административна услуга с човешка подкрепа.",
      points: [
        "Структуриране на официални писма",
        "Помощ при подаване на заявления",
        "Проверка на документи",
        "Организиране на документацията",
        "Проследяване на срокове",
        "Лична подкрепа",
        "Първи цифрови клиентски досиета",
      ],
      narrativ:
        "Учим се от реални административни случаи кои проблеми възникват най-често. Цел: да разберем и стандартизираме първите няколкостотин реални случая.",
    },
    {
      phase: "Phase 2",
      title: "Цифрова административна папка",
      status: "naechste-stufe",
      statusLabel: "Следващ етап на развитие",
      intro: "Клиентът не бива да събира отново личните си данни при всяко заявление.",
      points: [
        "Лично хранилище за документи",
        "Интелигентно сортиране на документи",
        "Структурирани клиентски профили",
        "Централен преглед на случаите",
        "Преглед на статусите",
        "Автоматични напомняния",
        "По-добро повторно използване на наличната информация",
      ],
      narrativ:
        "Цифровата административна папка се превръща в централно място за всички документи – подредено, лесно откриваемо и годно за повторна употреба.",
    },
    {
      phase: "Phase 3",
      title: "Автоматизирани стандартни процеси",
      status: "vision",
      statusLabel: "Визия",
      intro: "Стандартизираните административни процеси получават все повече технологична подкрепа – с човек в контролната точка.",
      points: [
        "Документът е разпознат",
        "Процесът е идентифициран",
        "Наличните документи са проверени",
        "Изискани са липсващите документи",
        "Случаят е подготвен",
        "Проверка от човек / клиент",
      ],
      narrativ:
        "Принципът „човек в цикъла“ остава водещ: технологията подготвя, а хората запазват контрол над всяка важна стъпка.",
    },
    {
      phase: "Phase 4",
      title: "Управление на житейски събития",
      status: "vision",
      statusLabel: "Дългосрочна визия",
      intro: "Вече не „От какъв формуляр имам нужда?“, а „Преместих се“.",
      points: [
        "Преместих се",
        "Родих дете",
        "Загубих работата си",
        "Пенсионирам се",
        "Член на семейството ми се нуждае от грижи",
      ],
      narrativ:
        "Antragsbruder разпознава от житейската ситуация съответните административни процеси – и показва какво трябва да се направи.",
    },
    {
      phase: "Phase 5",
      title: "Personal Administration OS",
      status: "vision",
      statusLabel: "Дългосрочна цел",
      intro: "Личен цифров административен офис за всеки гражданин.",
      points: [
        "Документи",
        "Институции",
        "Срокове",
        "Заявления",
        "Договори",
        "Семейство",
        "Житейски събития",
        "История на случаите",
      ],
      narrativ:
        "Едно място за цялата лична администрация на човек – изградено стъпка по стъпка, а не обещано наведнъж.",
    },
  ],
  ro: [
    {
      phase: "Phase 1",
      title: "Înțelegere & Ajutor",
      status: "jetzt",
      statusLabel: "Acum",
      intro: "Faza de lansare 2026 – Antragsbruder ca serviciu administrativ susținut de oameni.",
      points: [
        "Structurarea scrisorilor oficiale",
        "Ajutor la cereri",
        "Verificarea documentelor",
        "Organizarea actelor",
        "Urmărirea termenelor",
        "Sprijin personal",
        "Primele dosare digitale de client",
      ],
      narrativ:
        "Învățăm din cazuri administrative reale ce probleme apar de fapt cel mai des. Obiectiv: să înțelegem și să standardizăm primele câteva sute de cazuri reale.",
    },
    {
      phase: "Phase 2",
      title: "Dosarul administrativ digital",
      status: "naechste-stufe",
      statusLabel: "Următoarea etapă de dezvoltare",
      intro: "Clientul nu ar trebui să adune din nou datele personale pentru fiecare cerere.",
      points: [
        "Seif personal de documente",
        "Sortare inteligentă a documentelor",
        "Profiluri de client structurate",
        "Prezentare centralizată a cazurilor",
        "Prezentări de stare",
        "Mementouri automate",
        "Reutilizare mai bună a informațiilor existente",
      ],
      narrativ:
        "Dosarul administrativ digital devine punctul central pentru toate documentele – ordonat, ușor de regăsit și reutilizabil.",
    },
    {
      phase: "Phase 3",
      title: "Procese standard automatizate",
      status: "vision",
      statusLabel: "Viziune",
      intro: "Procesele administrative standardizate primesc tot mai mult sprijin tehnologic – cu omul ca punct de control.",
      points: [
        "Document recunoscut",
        "Proces identificat",
        "Documente existente verificate",
        "Documente lipsă solicitate",
        "Caz pregătit",
        "Verificare umană / de către client",
      ],
      narrativ:
        "Principiul „omul în buclă” rămâne valabil: tehnologia pregătește, oamenii păstrează controlul asupra fiecărui pas important.",
    },
    {
      phase: "Phase 4",
      title: "Administrarea evenimentelor de viață",
      status: "vision",
      statusLabel: "Viziune pe termen lung",
      intro: "Nu mai „De ce formular am nevoie?”, ci „M-am mutat.”",
      points: [
        "M-am mutat",
        "Am avut un copil",
        "Mi-am pierdut locul de muncă",
        "Mă pensionez",
        "Un membru al familiei are nevoie de îngrijire",
      ],
      narrativ:
        "Antragsbruder recunoaște din situația de viață procesele administrative relevante – și îți arată ce ai de făcut.",
    },
    {
      phase: "Phase 5",
      title: "Personal Administration OS",
      status: "vision",
      statusLabel: "Obiectiv pe termen lung",
      intro: "Un birou administrativ digital personal pentru fiecare cetățean.",
      points: [
        "Documente",
        "Instituții",
        "Termene",
        "Cereri",
        "Contracte",
        "Familie",
        "Evenimente de viață",
        "Istoricul cazurilor",
      ],
      narrativ:
        "Un singur loc pentru întreaga administrație privată a unei persoane – construit pas cu pas, nu promis dintr-o dată.",
    },
  ],
};

export const automationSteps: Record<Locale, string[]> = {
  de: ["Verstehen", "Standardisieren", "Digitalisieren", "Unterstützen", "Automatisieren"],
  en: ["Understand", "Standardize", "Digitize", "Support", "Automate"],
  ar: ["الفهم", "التوحيد القياسي", "الرقمنة", "الدعم", "الأتمتة"],
  tr: ["Anlamak", "Standartlaştırmak", "Dijitalleştirmek", "Desteklemek", "Otomatikleştirmek"],
  ru: ["Понять", "Стандартизировать", "Оцифровать", "Поддержать", "Автоматизировать"],
  uk: ["Зрозуміти", "Стандартизувати", "Оцифрувати", "Підтримати", "Автоматизувати"],
  pl: ["Zrozumieć", "Ustandaryzować", "Zdigitalizować", "Wesprzeć", "Zautomatyzować"],
  bg: ["Разбиране", "Стандартизиране", "Дигитализиране", "Подкрепа", "Автоматизиране"],
  ro: ["Înțelegere", "Standardizare", "Digitalizare", "Sprijin", "Automatizare"],
};
